routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\KamarController;
use App\Http\Controllers\PropertiController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\EditorController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('beranda');
});

Route::controller(BarangController::class)->name('barang.')->prefix('master-data/barang')->group(function () {
    Route::get(
        '/',
        'index'
    )->name('index');
    Route::get(
        'list',
        'listTabel'
    )->name('list');

    Route::get(
        'dalamfolder',
        'getDalamFolder'
    )->name('fileDalamFolder');
});


Route::controller(CustomerController::class)->name('customer.')->prefix('customer')->group(function () {
    Route::get('/', 'list')->name('list');
    Route::get('/Input', 'formInput')->name('form-input');
    Route::post('/simpandata', 'simpanData')->name('simpan-data');
});

Route::controller(KamarController::class)->name('kamar.')->prefix('list')->group(function () {
    Route::get('/', 'listKamar')->name('list');
    Route::get('/form-input', 'formInput')->name('form-input');
    Route::POST('/simpan-data', 'simpanData')->name('simpan-data');
    Route::get('/form-edit/{id}', 'formEdit')->name('form-edit');
    Route::Post('/edit/{id}', 'editData')->name('edit-data');
    Route::get('/delete-data/{id}', 'deleteData')->name('delete-data');
});

Route::controller(PropertiController::class)->name('properti.')->prefix('master/properti')->group(function () {
    Route::get('/', 'listproperti')->name('list');
    Route::get('/form', 'formInput')->name('form-input');
    Route::post('/simpandata', 'simpanData')->name('simpan-data');
    Route::get('/delete-data/{id}', 'deleteData')->name('delete-data');
});

Route::controller(RegisterController::class)->name('register.')->prefix('register')->group(function () {
    Route::get('/', 'formRegister')->name('form-register');
    Route::post('/simpan-register', 'simpanRegister')->name('simpan-register');
});

Route::controller(LoginController::class)->name('login.')->prefix('login')->group(function () {
    Route::get('/', 'formLogin')->name('form-login');
});

Route::controller(AdminController::class)->name('admin.')->prefix('admin')->group(function () {
    Route::get('/', 'BerandaAdmin')->name('beranda');
});

Route::controller(EditorController::class)->name('editor.')->prefix('editor')->group(function () {
    Route::get('/', 'BerandaEditor')->name('beranda');
});



// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/beranda.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    /* Tambahkan gaya khusus di sini */

    /* Misalnya: */
    body {
      background-color: #f8f9fa;
    }
    .jumbotron {
      background-color: #007bff;
      color: #fff;
    }
  </style>
  <title>Tampilan Beranda</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark pb-0">
    <a class="navbar-brand" href="#">Logo</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ route('admin.beranda') }}">Beranda</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Tentang</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Layanan</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Logout</a>
        </li>
      </ul>
    </div>
  </nav>

<p class="text-danger">
    @if(session('error'))
       {{ session('error') }}
    @endif
</p>


    <h1 class="text-center">Selamat Datang di Tampilan Admin</h1>




  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>